services:
  account-producer:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.account
    entrypoint: dockerize -wait tcp://kafka1:19092 -timeout 60s /app/account_producer
    container_name: account-producer
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    ports:
      - "14000:4000"
    environment:
      ENVRUN: docker
    networks:
      - flink-kafka-cluster-net

  customer_producer:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile.customer
    entrypoint: dockerize -wait tcp://kafka1:19092 -timeout 60s /app/customer_producer
    container_name: customer-producer
    depends_on:
      - kafka1
      - kafka2
      - kafka3
    ports:
      - "24000:4000"
    environment:
      ENVRUN: docker
    networks:
      - flink-kafka-cluster-net

  kafka1:
    image: confluentinc/cp-kafka
    container_name: kafka1
    hostname: kafka1
    ports:
      - "29092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: "INTERNAL://:19092,EXTERNAL://:9092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka1:19092,EXTERNAL://localhost:29092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_LOG_CLEANER_ENABLE: true
      KAFKA_DELETE_TOPIC_ENABLE: true
      CLUSTER_ID: bd669940-a465-483e-b99e-bec44fceb0ad
    #volumes:
    #  - ./kafka1_data:/var/lib/kafka/data
    networks:
      - flink-kafka-cluster-net

  kafka2:
    image: confluentinc/cp-kafka
    container_name: kafka2
    hostname: kafka2
    ports:
      - "39092:9092"
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: "INTERNAL://:19092,EXTERNAL://:9092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka2:19092,EXTERNAL://localhost:39092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_LOG_CLEANER_ENABLE: true
      KAFKA_DELETE_TOPIC_ENABLE: true
      CLUSTER_ID: bd669940-a465-483e-b99e-bec44fceb0ad
    #volumes:
    #  - ./kafka2_data:/var/lib/kafka/data
    networks:
      - flink-kafka-cluster-net

  kafka3:
    image: confluentinc/cp-kafka
    container_name: kafka3
    hostname: kafka3
    ports:
      - "49092:9092"
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_LISTENERS: "INTERNAL://:19092,EXTERNAL://:9092,CONTROLLER://:9093"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka3:19092,EXTERNAL://localhost:49092"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka1:9093,2@kafka2:9093,3@kafka3:9093"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 3
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 2
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: true
      KAFKA_LOG_CLEANER_ENABLE: true
      KAFKA_DELETE_TOPIC_ENABLE: true
      CLUSTER_ID: bd669940-a465-483e-b99e-bec44fceb0ad
    #volumes:
    #  - ./kafka3_data:/var/lib/kafka/data
    networks:
      - flink-kafka-cluster-net

  jobmanager:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: jobmanager
    ports:
      - "8081:8081"
    command: jobmanager
    volumes:
      - ./jars/:/opt/flink/jars
      - ./logs/flink/jm:/opt/flink/temp
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    networks:
      - flink-kafka-cluster-net

  taskmanager1:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: taskmanager1
    depends_on:
      - jobmanager
    command: taskmanager
    volumes:
      - ./logs/flink/tm1:/opt/flink/temp
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
    networks:
      - flink-kafka-cluster-net

  taskmanager2:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    container_name: taskmanager2
    depends_on:
      - jobmanager
    command: taskmanager
    volumes:
      - ./logs/flink/tm2:/opt/flink/temp
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
    networks:
      - flink-kafka-cluster-net

networks:
  flink-kafka-cluster-net:
    driver: bridge
