docker:
  brokers:
    - "kafka1:19092"
    - "kafka2:19092"
    - "kafka3:19092"
  topics:
    - "transactions"
    - "customers"
    - "accounts"
    - "transactions.credits"
    - "transactions.debits"
