local:
  brokers:
    - "localhost:29092"
    - "localhost:39092"
    - "localhost:49092"
  topics:
    - "transactions"
    - "customers"
    - "accounts"
    - "transactions.credits"
    - "transactions.debits"
